### ISSUE TITLE
Can you make this for Firefox?

### ISSUE THREAD

**Issue by ghost** [keyboardslayer/rarbg-thumbnails#2]
I love rarbg-thumbnails but recently I went from chrome to firefox and I miss this extension so badly.

**Comment by nimbling** [comment]
I've committed it to Firefox under this listing:
https://addons.mozilla.org/en-US/firefox/addon/rarbg-thumbnails-public-v/
It's still in approval as of this writing.

In other news: it needed exactly no other coding to work: just zip this folders' contents, rename the zip to .xpi and install that in your firefox.

**Comment by keyboardslayer** [comment]
@nimbling Thanks for testing it! 

I'll submit the Firefox version and keep it in sync with this repo and post the link once it is approved.

**Comment by keyboardslayer** [comment]
Please install it from here: https://addons.mozilla.org/en-US/firefox/addon/rarbg-thumbnails-display/
